services:
  - type: web
    name: sistema-facturacion-backend
    env: python
    plan: free
    buildCommand: "pip install -r requirements.txt"
    autoDeploy: true
    envVars:
      - key: FLASK_ENV
        value: production
      - key: DB_HOST
        sync: false
      - key: DB_USER
        sync: false
      - key: DB_PASS
        sync: false
      - key: DB_NAME
        sync: false
